//
//  Superhero_CardApp.swift
//  Superhero Card
//
//  Created by Pasquale Vittoriosi on 08/09/22.
//

import SwiftUI

/*
 Do not edit this file!
 It is required for the next part of the workshop.
*/
@main
struct Superhero_CardApp: App {
    
    var body: some Scene {
        WindowGroup {
            VStack {
                SuperheroCardView()
                
                Spacer()
                
                ShareLink(
                    item: SuperheroCardView().snapshot(),
                    preview: SharePreview("My Superhero Card", image: SuperheroCardView().snapshot())
                )
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
                
                Spacer()
            }
        }
    }
    
}

extension View {
    
    @MainActor
    func snapshot() -> Image {
        let renderer = ImageRenderer(content: self)
        return Image(uiImage: renderer.uiImage!)
    }
    
}
